---
- name: Build Switch configuration
  hosts: "{{ target_hosts }}"
  gather_facts: false

  # vars_files:
  #   - "../global_vars/global_dc_vars.yml"

  tasks:

    - name: Import Global Vars
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/global_dc_vars.yml"

    - name: Generate Structured Variables per Device
      import_role:
        name: arista.avd.eos_designs

    - name: Generate Intended Config and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen