name: Deploy updates

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    env:
      LABPASSPHRASE: ${{ secrets.LABPASSPHRASE }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: echo "Hello World!"

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Setup Python
      #   uses: actions/setup-python@v3

      # - name: Run pre-commit on files
      #   uses: pre-commit/action@v3.0.0

      # - name: Start containers
      #   run: docker-compose -f "docker-compose.yml" up -d --build

      # - name: Build and deploy
      #   run:  >
      #     docker-compose run atd-cicd
      #     make build-site-1 build-site-2 cvp-site-1 cvp-site-2

      # - name: Stop containers
      #   if: always()
      #   run: docker-compose -f "docker-compose.yml" down
