name: Deploy updates

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    env:
      LABPASSPHRASE: ${{ secrets.LABPASSPHRASE }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: echo "Hello World!"

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Setup Python
      #   uses: actions/setup-python@v3

      # - name: Run pre-commit on files
      #   uses: pre-commit/action@v3.0.0

      # - name: Check paths for sites/site_1
      #   uses: dorny/paths-filter@v2
      #   id: filter-site1
      #   with:
      #     filters: |
      #       workflows:
      #         - 'sites/site_1/**'

      # - name: Check paths for sites/site_2
      #   uses: dorny/paths-filter@v2
      #   id: filter-site2
      #   with:
      #     filters: |
      #       workflows:
      #         - 'sites/site_2/**'

      # - name: Start containers
      #   run: docker-compose -f "docker-compose.yml" up -d

      # - name: Build and deploy site1
      #   run: >
      #     docker-compose run atd-cicd
      #     make build-site-1 cvp-site-1
      #   if: steps.filter-site1.outputs.workflows == 'true'

      # - name: Build and deploy site2
      #   run: >
      #     docker-compose run atd-cicd
      #     make build-site-2 cvp-site-2
      #   if: steps.filter-site2.outputs.workflows == 'true'

      # - name: Stop containers
      #   if: always()
      #   run: docker-compose -f "docker-compose.yml" down
